# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 24f37028167582a3a19d672a978cae5b392ee51ecb385be107b1e8a347b7d3708925eadc7b21f923ccbef6b51f93d96bffc06fb0e5d9eb6b4aa3413d3787b65e

test:
  secret_key_base: a44662069e9d675cdd83047ee61aab49b8c0a66efaca5475e97242140cb0b6bc7efe928373978339cb24a82928b30a1283c3067cdf89bb2adb733ac1e6c62999

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
